Create book repository
wolox-training/al-java pull request #4
Opened 2020-05-29 18:20 UTC by alanlamaswolox

## Summary

Created repository for Books

## Trello card
[link](https://trello.com/c/tonIrXIh/15-crear-un-repositorio-de-books)

2020-05-31 17:51 UTC, Gianni-Nicolas requested changes
Great! 😃

2020-05-31 17:51 UTC, GNico95 commented on src/main/java/wolox/training/models/Book.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
In Postgres when GenerationType.AUTO is used, it generates an incremental IDs shared between the schema tables. This happens only for this database engine. To generate independent IDs for each table use GenerationType.SEQUENCE.
```suggestion
    @GeneratedValue (strategy = GenerationType.SEQUENCE, generator = "BOOK_SEQ")            
    @SequenceGenerator(name = "BOOK_SEQ", sequenceName = "BOOK_SEQ")
```

2020-06-01 22:08 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-06-02 13:56 UTC, Gianni-Nicolas approved these changes

2020-06-02 13:58 UTC, AleFalcon approved these changes
It's Ok

2020-06-02 14:02 UTC, merged