CRUD methods for bookController and BookNotFoundException
wolox-training/al-java pull request #5
Opened 2020-06-01 16:01 UTC by alanlamaswolox

## Summary
Created CRUD methods and BookNotFoundException

## Trello card
[link](https://trello.com/c/tlxJ7lhM/18-crear-las-operaciones-crud-de-book)

2020-06-02 14:14 UTC, Gianni-Nicolas requested changes
Good job, leave you two little comments 😄

2020-06-02 14:14 UTC, GNico95 commented on src/main/java/wolox/training/controllers/BookController.java
> +
A good practice mentioned at this point in the training is to add java docs in each of the controllers. They are also used to describe and document methods that may be considered complex.

2020-06-02 14:14 UTC, GNico95 commented on src/main/java/wolox/training/controllers/BookController.java
> +        bookRepository.save(book);
Add a book return to show the book you added at the end of the transaction

2020-06-02 14:56 UTC, AleFalcon submitted a review, later dismissed
It's okay with comments by Nico

2020-06-04 12:46 UTC, Gianni-Nicolas requested changes

2020-06-04 12:46 UTC, GNico95 commented on src/main/java/wolox/training/controllers/BookController.java
> +    /**
One of the most important things about javadocs is the explanation of the method being documented.
That description would be missing, indicating the purpose of the method in each of the documented methods.

2020-06-04 17:30 UTC, Gianni-Nicolas approved these changes

2020-06-04 17:33 UTC, AleFalcon approved these changes

2020-06-04 18:18 UTC, merged