Created User repository
wolox-training/al-java pull request #7
Opened 2020-06-01 23:01 UTC by alanlamaswolox

## Summary

A user repository with a method that finds one user by username

## Trello card

[link](https://trello.com/b/1EiY4hHX/training-java-alan-lamas)

2020-06-02 14:36 UTC, Gianni-Nicolas requested changes
Good job, I marked only one detail

2020-06-02 14:36 UTC, GNico95 commented on src/main/java/wolox/training/repositories/UserRepository.java
> +    Optional<User> findFirstByUsername(final String username);
Add java docs in each query of the user and book repositories.

2020-06-02 15:02 UTC, AleFalcon approved these changes
It's okay with comment by Nico

2020-06-04 12:48 UTC, Gianni-Nicolas requested changes

2020-06-04 12:48 UTC, GNico95 commented on src/main/java/wolox/training/repositories/BookRepository.java
> +     *
One of the most important things about javadocs is the explanation of the method being documented.
That description would be missing, indicating the purpose of the method in each of the documented repositories.

2020-06-04 21:56 UTC, Gianni-Nicolas approved these changes

2020-06-04 22:19 UTC, merged